// src/constants/categories.js
export const categories = [
  "Xe cộ",
  "Nhà đất",
  "Việc làm",
  "Điện thoại & Máy tính bảng",
  "Máy tính & Laptop",
  "Điện tử & Điện lạnh",
  "Đồ gia dụng",
  "Nội thất & Trang trí",
  "Thời trang & Phụ kiện",
  "Giày dép",
  "Đồng hồ & Trang sức",
  "Mẹ & Bé",
  "Đồ chơi & Sưu tầm",
  "Sách & Văn phòng phẩm",
  "Sức khỏe & Làm đẹp",
  "Thú cưng & Vật nuôi",
  "Thực phẩm & Đồ uống",
  "Dịch vụ",
  "Cho thuê - Cần thuê",
  "Cần mua - Trao đổi",
  "Du lịch & Vé",
  "Khác",
];
